# Base image with Flutter
FROM cirrusci/flutter:3.24.3

# Set working directory
WORKDIR /app

# Copy all Flutter project files into container
COPY . .

# Get dependencies
RUN flutter pub get

# Build app bundle (.aab) for Play Store
RUN flutter build appbundle
